AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function URL Demo

Resources:
  ServerlessLambdaFnURLFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs14.x
      FunctionUrlConfig:
        AuthType: NONE
        # Cors:
        #   AllowOrigins:
        #     - "*"

  CfnLambdaFnURLFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs14.x

  LambdaURL:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref CfnLambdaFnURLFn
    DependsOn: CfnLambdaFnURLFn
#       Cors:
#         AllowOrigins:
#           - "*"
#       Qualifier: live
